[package]
name = "bm_null"
version = "0.1.0"
authors = ["Minhong Yun <mhyun@rice.edu>"]
edition = "2018"

[dependencies]
libc = "0.2"
hwloc = "0.3.0"
perfcnt = "0.5.0"

[dependencies.core_affinity]
git = "https://github.com/Ramla-I/core_affinity_rs.git"